### ISSUE TITLE
Creare la versione superlong dei file di disabilità in cifre - tipo 1

### ISSUE THREAD

**Issue by aborruso** [ondata/disabled-data#1]
Il primo tipo di output ha questa struttura

| territorio | valore | descrizione | anno | gerarchia |
| --- | --- | --- | --- | --- |
| Molise | 6 | Tirocini avviati al 31 dicembre (valori assoluti) | 2009 | regionale |
| Reggio di Calabria | 68411 | Numero dei beneficiari di pensioni per le persone con disabilità | 2003 | provinciale |
| Teramo | 30351 | Numero dei beneficiari di pensioni per le persone con disabilità | 2004 | provinciale |
| Regione Piemonte | 266680 | Numero dei beneficiari di pensioni per le persone con disabilità | 2009 | provinciale |
| Agrigento | 57116 | Numero dei beneficiari di pensioni per le persone con disabilità | 2005 | provinciale |
| Calabria | 6 | Tirocini avviati al 31 dicembre (valori assoluti) | 2006 | regionale |
| Ancona | 40197 | Numero dei beneficiari di pensioni per le persone con disabilità | 2009 | provinciale |
| Potenza | 56465 | Numero dei beneficiari di pensioni per le persone con disabilità | 2004 | provinciale |
| Monza e della Brianza | 0 | Numero dei beneficiari di pensioni per le persone con disabilità | 2005 | provinciale |
| Carbonia-Iglesias | 14084 | Numero dei beneficiari di pensioni per le persone con disabilità | 2008 | provinciale |

`descrizione` è il nome della tavola scaricata e `gerarchia` il livello gerarchico territoriale di quella tavola.

@simonabisiani mi rispondi con un esempio di poche righe, sul come vorresti l'output "superlong". Soltanto il nome del territorio e poi tutto chiave, valore (non credo, ma chiedo)?

**Comment by simonabisiani** [comment]
meglio tardi che mai (o prova per me per l'uso di GitHub issues): la struttura qua sopra va benissimo.
