### ISSUE TITLE
Estrarre lista codici, valori per i dataset Eurostat

### ISSUE THREAD

**Issue by aborruso** [ondata/disabled-data#10]
Ciao @aborruso,

ci ho finalmente dato un'occhiata - ho navigato un paio di files e mi sembra tutto a posto, completo di dettagli, e nel formato migliore possibile. 

Se riesci a fare un file di risorse con il significato dei codici usati sarebbe super, ma non c'è fretta e in emergenza me li vado a cercare io, siccome per ogni visualizzazione che creo vado comunque sempre a leggermi i metadata ecc :)

Grazie per il lavoro svolto velocemente!
Non so se vuoi chiudere la issue già adesso, ho aspettare i file di risorse; come preferisci :)

_Originally posted by @simonabisiani in https://github.com/ondata/disabled-data/issues/9#issuecomment-1200964959_

**Comment by simonabisiani** [comment]
ciao @aborruso,

ho notato mancava una variabile nella lista, "sex". L'ho aggiunta al file dict.txt. Potresti aiutarmi a estrarre il .dict e creare il json lines file per quella variabile?
