### ISSUE TITLE
Estrazione tabella I.STAT

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#12]
Ciao @aborruso, sarebbe possibile aggiungere questa tabella al repo? http://dati.istat.it/?lang=it&SubSessionId=f520027c-76f3-4151-a078-87c3f4e40aa6

Si tratta dell'incidenza di donne con disabilità nelle donne che hanno subito violenza, un'indagine del 2014 i cui dati non sono riportarti in disabilitàincifre.

**Comment by aborruso** [comment]
ciao @simonabisiani l'URL è corretto?

Mi apre la home

![image](https://user-images.githubusercontent.com/30607/188888176-3f507c12-bb3e-4a2d-811b-74d2e92f1595.png)

**Comment by simonabisiani** [comment]
Ciao! questo funziona? http://dati.istat.it/?lang=it&SubSessionId=f520027c-76f3-4151-a078-87c3f4e40aa6

**Comment by simonabisiani** [comment]
Credo di aver trovato il link corretto @aborruso: http://dati.istat.it/index.aspx?queryid=46534

**Comment by aborruso** [comment]
Cara @simonabisiani questo dataset non era scaricabile tramite API. Allora mi sono informato e mi hanno detto:

> visto che è stato pubblicato il nuovo cubo di diffusione "Donne che hanno subito violenza - caratteristiche demografiche e abitudini", le informazioni contenute nei cubi  "DCCV_VIOLENZADONNEPART" e  "DCCV_VIOLENZADONNE" risultavano ridondanti; perciò sono stati oscurati e i dati con un maggior dettaglio informativo possono essere reperiti nel DS "Donne che hanno subito violenza - caratteristiche demografiche e abitudini" (con codice DCCV_VIOL_CARAT)

Quindi ho scaricato `DCCV_VIOL_CARAT` e l'output è qui https://github.com/ondata/disabled-data/blob/main/data/istat/DCCV_VIOL_CARAT/78_1112.csv

Anche qui, in modalità diverse, abbiamo dei dizionari da scaricare e sono qui https://github.com/ondata/disabled-data/tree/main/data/istat/DCCV_VIOL_CARAT/dict

La cosa bella è che qui, è già in due lingue, ad esempio https://github.com/ondata/disabled-data/blob/main/data/istat/DCCV_VIOL_CARAT/dict/ATTIVITA_TEMPOLIB.jsonl
