### ISSUE TITLE
Alcune mancanze in certe tabelle

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#13]
Ciao @aborruso, scusami se ti tormento con questi dati!

Ho notato che in alcune tabelle alcuni variabili non sono specificate. 

Nello specifico, nei casi in cui serve a me si tratta di 6 tabelle, tutte contenute all'interno del file [6_01.csv](https://github.com/ondata/disabled-data/blob/main/data/disabilita-in-cifre/processing/6_01.csv):
- Persone per gravità delle limitazioni nella attività abitualmente svolte e stato di salute percepito (valori percentuali)
- Tutte le 4 tabelle sull'utilizzo dei trasporti (treno, automobile, trasporto pubblico urbano, trasporto pubblico extraurbano)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e tipologia familiare (valori percentuali)

Prima di riportarti l'errore, ti faccio solo notare che le ultime 5 tabelle sono incluse nella mia richiesta di estrazione ulteriori variabili. 
Pertanto, se l'errore non si ripete là, mi servirebbe solo la correzione della prima tabella sullo stato di salute autopercepito.

Andiamo all'errore: manca la regione di riferimento. La colonna che solitamente la indica, qua indica invece un'altra variabile.
Ecco un esempio qua sotto con lo stato di salute autopercepito, marchiato in blu. In giallo, invece, una tabella dove l'errore non ritorna siccome la regione è indicata. Di fatto il problema credo sia dovuto all'alto numero di variabili:

![image](https://user-images.githubusercontent.com/52672651/189886011-ca54be3e-86d1-49b1-8ac5-1fb9bf4c6edb.png)
![image](https://user-images.githubusercontent.com/52672651/189886163-70624477-e117-4f4d-b8f8-0cc26423c9dd.png)

Se per caso sono io che mi sono svista qualcosa, o se servono ulteriori spiegazioni, dimmi pure!

Alla domanda finale: è possibile aggiungere la regione a quella tabella (e di fatto poi anche alle tabelle che ti avevo già chiesto di ri-estrarre con le ulteriori variabili)?

**Comment by aborruso** [comment]
Cara @simonabisiani ,
quando ricevo questi messaggi mi dispiaccio, mi sento in colpa :)

La gran parte del download e processing è automatizzata, altrimenti diventavo scemo.

Per automatizzarla, ho simulato le interazioni a schermo, e le ho poi mappate con regole di scraping per farle sulle centinaia di possibilità.

Guarda ad esempio questo caso:

- seleziono l'anno (2019)
- seleziono il territorio (regionale)
- faccio il download.

Guardalo qui https://youtu.be/oH-ZV0WC7aE

Come vedi, anche se ho scelto regionale, non ci sono dati sulle regioni. 
Prova a rifare il tutto come me.

Lo script lo mappa come regionale, perché lui da regionale è passato.

La sostanza però è come dici: il sito non funziona bene, e l'export per regioni va fatto diversamente.

Aggiungerei questa all'altra richiesta. Che ne dici?

**Comment by simonabisiani** [comment]
Ho visto ora @aborruso, grazie per la spiegazione! Ho cercato un altro modo di ottenere la lista intera delle regioni, ma sembra che l'unico modo sia entrare nella tabella, cliccare la freccetta su regione Piemonte, e scaricare le tabelle delle regioni una ad una. C'è davvero da andar scemi con sto database :) 

![image](https://user-images.githubusercontent.com/52672651/189892878-43b58b1d-bf04-4ad2-a9f3-cd6e1ffbbc87.png)


Pensavo, siccome il taglio nazionale è facilmente estraibile, che se per ottenere il taglio regionale bisogna donare un rene, ci facciamo bastare il taglio nazionale. Quello pero' non lo abbiamo ancora estratto per queste tabelle, quindi dovremmo estrarlo (questo per tutte e sei le tabelle sopracitate). 

Dimmi tu se andiamo di taglio nazionale o se vuoi provare a estrarre quello regionale, lascio a te il giudizio.

**Comment by aborruso** [comment]
> Dimmi tu se andiamo di taglio nazionale o se vuoi provare a estrarre quello regionale, lascio a te il giudizio.

Proviamoci!
