### ISSUE TITLE
Ultime tabelle taglio nazionale

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#18]
Ciao @aborruso, come promesso, ecco la nuova issue che merge le issues #13 e #11.

Ti richiedo di estrarmi il taglio nazionale, provvisto di ulteriore dettaglio a livello di inclusione di variabili aggiuntive, delle seguenti tabelle. I link portano a serie storiche. A volte non c'è bisogno di "sfogliare", altre volte si sfoglia per una variabile (e.g. "sesso") a volte per due (e.g. "sesso" e "tipo di limitazione"). Se questo è un problema dimmi pure e semplifico ulteriormente la ricerca (e.g. togliendo una delle variabili da sfogliare).

| URL                                                                                                                                                                                      | TEMA       | TABELLA                                                                                                                                               | VARIABILI DA ESTRARRE               |
|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|-------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------|
| https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3091DM09OG0000000&p=0&sp=null&l=0&exp=0&st=1VVO                                                   | Istruzione | Alunni con disabilità della scuola secondaria di II grado (valori per 100 alunni con le stesse caratteristiche)                                       | Tipo di scuola superiore            |
| https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2k4a94&a2=_-&n=$$$9$$$$$$$&o=4C&v=1V30918309OG0000000&p=0&sp=null&l=0&exp=0&st=1VVO                                                 | Istruzione | Alunni con disabilità (valori per 100 alunni con le stesse caratteristiche)                                                                           | Ordine scolastico                   |
| https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2k4a94&a2=_-&n=$$$9$$$$$$$&o=4C&v=1V30918209OG0000000&p=0&sp=null&l=0&exp=0&st=1VVO                                                 | Istruzione | Alunni con disabilità (valori per 100 alunni con le stesse caratteristiche)                                                                           | Tipo di gestione                    |
| link a pagina "Maschi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3091OU09OG00000000000&p=0&sp=null&l=0&exp=1&st=0FVO                       | Istruzione | Persone di 25 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e titolo di studio (valori percentuali)                     |  Sesso                              |
| link a "Accesso con rampe" e "Infanzia": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3091MH09OG00000000000&p=0&sp=null&l=0&exp=1&st=07VO      | Istruzione | Numero scuole per caratteristiche edificio scolastico (Valori percentuali)                                                                            | Caratteristiche edificio scolastico |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3092C109OG00000000000&p=0&sp=null&l=0&exp=1&st=0FVO | Lavoro     | Persone di 15 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e condizione professionale dichiarata (valori percentuali)  | Sesso                               |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3092BL09OG00000000000&p=0&sp=null&l=0&exp=0&st=0FVO | Lavoro     | Persone occupate di 15 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e posizione nella professione (valori percentuali) | Sesso                               |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V3092A109OG00000000000&p=0&sp=null&l=0&exp=0&st=0FVO | Famiglie   | Persone per gravità delle limitazioni nelle attività abitualmente svolte e tipologia familiare (valori percentuali)                                   | Sesso                               |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V30925509OG00000000000&p=0&sp=null&l=0&exp=0&st=0FVO | Trasporto  | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e trasporto pubblico extraurbano (valori percentuali)       | Sesso                               |
| link a pagina "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V30925B09OG000000000&p=0&sp=null&l=0&exp=1&stAll=1              | Trasporto  | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e utilizzo del treno (valori percentuali)                   | -                                   |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V30924P09OG00000000000&p=0&sp=null&l=0&exp=1&st=0FVO | Trasporto  | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e utilizzo trasporto pubblico urbano (valori percentuali)   | Sesso                               |
| link a pagina "Maschi" e "limitazioni gravi": https://disabilitaincifre.istat.it/dawinciMD.jsp?a1=u2i4a94&a2=_-&n=$$$9$$$$$$$&o=&v=1V30924D09OG00000000000&p=0&sp=null&l=0&exp=1&st=0FVO | Trasporto  | Persone di 18 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e uso automobile come conducente (valori percentuali)       | Sesso                               |

**Comment by aborruso** [comment]
Ciao @simonabisiani ho estratto i 12 dataset che mi hai indicato. Sotto l'[anagrafica](https://github.com/ondata/disabled-data/blob/main/data/issue-18/anagrafica.md).

Alcune note:

- al momento ho lasciato in wide, per aver un tuo rapido check;
- ho lasciato il carattere `#`, per dare di quei casi in cui a monte è definito così;
- i dati grezzi, sorgente, in xls sono [qui](https://github.com/ondata/disabled-data/tree/main/data/issue-18/raw);
- nei CSV di output ho lasciato traccia sia del nome del file, che del nome del foglio (è utile per i multi foglio).

Fammi sapere se sono ok, e come li vuoi ristrutturati.

Grazie e buon lavoro


## Anagrafica

| file | nomeDataset |
| --- | --- |
| [g1V3091DM09OG0000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3091DM09OG0000000_st.csv) | Alunni con disabilità della scuola secondaria di II grado (valori per 100 alunni con le stesse caratteristiche) per tipo scuola superiore |
| [g1V30918309OG0000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30918309OG0000000_st.csv) | Alunni con disabilità (valori per 100 alunni con le stesse caratteristiche) per ordine scolastico |
| [g1V30918209OG0000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30918209OG0000000_st.csv) | Alunni con disabilità (valori per 100 alunni con le stesse caratteristiche) per tipo di gestione della scuola |
| [g1V3091OU09OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3091OU09OG00000000000_st.csv) | Persone di 25 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e titolo di studio (valori percentuali) per sesso |
| [g1V3091MH09OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3091MH09OG00000000000_st.csv) | Numero scuole per caratteristiche edificio scolastico (Valori percentuali) per ambiente scolastico |
| [g1V3092C109OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3092C109OG00000000000_st.csv) | Persone di 15 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e condizione professionale dichiarata (valori percentuali) per sesso |
| [g1V3092BL09OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3092BL09OG00000000000_st.csv) | Persone occupate di 15 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e posizione nella professione (valori percentuali) per sesso |
| [g1V3092A109OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V3092A109OG00000000000_st.csv) | Persone per gravità delle limitazioni nelle attività abitualmente svolte e tipologia familiare (valori percentuali) per sesso |
| [g1V30925509OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30925509OG00000000000_st.csv) | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e trasporto pubblico extraurbano (valori percentuali) per sesso |
| [g1V30925B09OG000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30925B09OG000000000_st.csv) | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e utilizzo del treno (valori percentuali) |
| [g1V30924P09OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30924P09OG00000000000_st.csv) | Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e utilizzo trasporto pubblico urbano (valori percentuali) per sesso |
| [g1V30924D09OG00000000000_st.csv](https://github.com/ondata/disabled-data/blob/main/data/issue-18/processing/g1V30924D09OG00000000000_st.csv) | Persone di 18 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e uso automobile come conducente (valori percentuali) per sesso |

**Comment by simonabisiani** [comment]
ciao  @aborruso, ho scritto istruzioni per creazione widgets basate sui dati come sono ora. Non credo Massi (il dev che se ne occupa) avra' problemi ad implementarle. 

Pertanto possiamo chiudere questa issue.

Grazie mille per l'estrazione!
Spero non sia stata troppo rognosa.
