### ISSUE TITLE
Dataset "eta": duplicato oppure mancano dati regionali

### ISSUE THREAD

**Issue by danielrampanelli** [ondata/disabled-data#20]
Può essere che il dataset `a1-eta` sia per sbaglio una copia di `a1-eta-nazionale`? Sono di fatto identici e in `a1-eta` mancano dati sulle varie regioni.

**Comment by aborruso** [comment]
Ciao @danielrampanelli grazie per la nota.

Per come è fatto il sito, lo scraping automatico (ma anche fatto a mano dall'utente) produce output nazionali, anche se la richiesta è diversa.

@simonabisiani sa di questo tema, e mi ha fatto su questo una proposta di rinunciare al momento ai dati regionali.
Chiedo a Simona di commentare in tal senso. 

Io ho una issue assegnata correlata, che chiuderò sabato.

**Comment by danielrampanelli** [comment]
Ciao, scusa siccome ho visto che erano stati utilizzati nella dashboard (e generavi dati "doppi") ho dato per scontato che il dataset era da usare. Potevo effettivamente fare un check con @simonabisiani prima, mea culpa.

**Comment by simonabisiani** [comment]
Sì, nel caso specifico di questa tabella tralasciamo i dati regionali (e anche in altri casi che corrispondono alle rimanenti visualizzazioni che abbiamo da fare). Quindi basta che usiamo una delle due tabelle e ignoriamo l'altra :)
