### ISSUE TITLE
Lista tabelle dati da estrarre sotto "Amministrativa - nazionale"

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#4]
Ciao @aborruso :)

Innanzitutto ho cercato di inquadrare quante tabelle esistono sotto Amministrativa tra taglio Nazionale e taglio Regionale.

| anno | nazionale | regionale |
|------|-----------|-----------|
| 2003 | 3         | 3         |
| 2004 | 5         | 5         |
| 2005 | 5         | 5         |
| 2006 | 9         | 9         |
| 2007 | 16        | 16        |
| 2008 | 24        | 24        |
| 2009 | 66        | 38        |
| 2010 | 71        | 42        |
| 2011 | 71        | 42        |
| 2012 | 68        | 38        |
| 2013 | 68        | 40        |
| 2014 | 68        | 40        |
| 2015 | 64        | 37        |
| 2016 | 64        | 37        |
| 2017 | 65        | 38        |
| 2018 | 66        | 38        |
| 2019 | 50        | 24        |

Da lì ho preso due anni a caso, 2009 e 2018, e guardato quali tabelle esistono sotto a Nazionale che mancano sotto a Regionale.
Di queste ho tenuto le tabelle che mi interessano per la dashboard.

Esse sono, in ordine di Release di uscita nella dashboard e con tematica di appartenenza tra parentesi:

**LUGLIO (Vita sociale)**
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e livello di soddisfazione per le relazioni familiari (valori percentuali
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e soddisfazione per il tempo libero (valori percentuali)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e soddisfazione per le relazioni amicali (valori percentuali)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e partecipazione culturale (valori percentuali)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e partecipazione sociale (valori percentuali)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e pratica sportiva (valori percentuali)

**SETTEMBRE (Istruzione, Lavoro e Occupazione)**
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e titolo di studio (valori percentuali)
- f.1 Persone per gravità delle limitazioni nelle attività abitualmente svolte e condizione professionale dichiarata (valori percentuali)
- f.2 Persone occupate per gravità delle limitazioni nelle attività abitualmente svolte e posizione nella professione dichiarata (valori percentuali)

**NOVEMBRE (Famiglie)**
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e ruolo familiare (valori percentuali)
- Persone per gravità delle limitazioni nelle attività abitualmente svolte e tipologia familiare (valori percentuali)

Mi chiedo se nell'estrazione di queste tabelle vale la pena infilarci anche quelle che mancano su taglio nazionale sull'uso dei trasporti? di fatto esistono sia sotto taglio regionale che nazionale. Pero' magari estraendole qua si risolve il problema da te riscontrato? Vedi tu :)

**Comment by aborruso** [comment]
Ciao @simonabisiani ho scaricato i circa 800 dati xls nazionali.

E da questi ho estratto quelli per luglio che mi chiedevi: https://github.com/ondata/disabled-data/blob/main/data/disabilita-in-cifre/processing/6-luglio.csv

Per chiudere aspetto un tuo ok

**Comment by simonabisiani** [comment]
Ciao, sì dovrebbero essere gli stessi. Invece di copiare e incollare i nomi dalla lista "Tavola", sono tornata sotto a "Oggetti" per poterne fare di più a tempo - non mi sono accorta i nomi fossero accorciati!

**Comment by aborruso** [comment]
> E da questi ho estratto quelli per luglio che mi chiedevi: https://github.com/ondata/disabled-data/blob/main/data/disabilita-in-cifre/processing/6-luglio.csv

Ciao @simonabisiani aspetto un riscontro su questo.

Grazie

**Comment by simonabisiani** [comment]
Mi sembra ci siano tutti! Grazie mille @aborruso :) Chiudo!
