### ISSUE TITLE
Ottenimento di informazioni su ulteriori variabili

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#5]
Ciao @aborruso, 

come menzionato in mail, sarei interessata anche a informazioni dettagliate su "Sesso" e "Classe di Età" in alcuni casi. Le prime due tabelle hanno priorità, e se hai tempo mi interesserebbero anche le altre due. Per ogni tabella ho listato in orizzontale quali variabili mi interessano.

Al momento ho guardato solo la release di Luglio, possiamo rifare questo processo per la release di Settembre e Novembre, dovessi voler retrieve di nuovo questi dettagli per alcune tabelle?

Ti listo i casi qua sotto:

| tabella                                                                                                                                          | variabile di interesse 1 | variabile di interesse 2 |
|--------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------|--------------------------|
| a.1 Persone per gravità delle limitazioni nelle attività abitualmente svolte (valori assoluti in migliaia)                                       | Sesso                    | Classe di età            |
| a.2 Persone per gravità delle limitazioni nelle attività abitualmente svolte (valori percentuali)                                                | Sesso                    | Classe di età            |
| Persone di 14 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e soddisfazione relazioni amicali (valori percentuali) | Sesso                    | Classe di età            |
| Persone di 3 anni e più per gravità delle limitazioni nelle attività abitualmente svolte e pratica sportiva (valori percentuali)                 | Sesso                    | Classe di età            |

**Comment by aborruso** [comment]
Ciao @simonabisiani ,
c'è da fare un po' di pulizia, ma mi sembrano già lavorabili. In ogni caso, fammi eventuali note.

Per una delle tavole non c'è il dettaglio di età per regione.

Li trovi qui https://github.com/ondata/disabled-data/tree/main/data/disabilita-in-cifre/processing/a1-a2

**Comment by simonabisiani** [comment]
Ciao @aborruso, sto creando le visualizzazioni con i dati estratti e cercavo una figura specifica per le tabelle su sesso e età con i valori assoluti. È il numero di persone con limitazioni gravi intervistate ogni anno. Uso quella figura per calcolare delle percentuali e visualizzare la composizione per età e sesso delle persone con disabilità. 

![Screenshot 2022-07-04 121030](https://user-images.githubusercontent.com/52672651/177134464-8cf5ea7a-bd11-4ffb-ba6d-00396e3e9c56.png)

Sai se la trovo da qualche parte? Cercandola non la trovo, e non riesco a trovare i dati grezzi su queste tabelle.

Grazie!

**Comment by aborruso** [comment]
Ciao @simonabisiani stavolta non sono sicuro di averti capito. Nel senso che mi sembra che mi stai chiedendo i dati nazionali di a1 e a2 con sesso e età.
L'ho chiusa da poco ed ad esempio la tabella con i raw data di a1 nazionali è qui https://github.com/ondata/disabled-data/blob/main/data/disabilita-in-cifre/processing/a1-a2/a1-eta-nazionale.csv

Nella tua immagine è diverso lo schema, perché pivotizzata per età, mentre nel mio output è long sull'età.

Detto in altre parole, i dati mi sembra che adesso ci siano. Li vuoi trasformati in qualche modo?
Se sì, mi fai per favore nuova issue?

Grazie

**Comment by simonabisiani** [comment]
Ciao @aborruso, 

hai assolutamente ragione, la stessa figura si trova nel taglio nazionale. 

Per l'esempio fatto sopra, la figura la trovo qui:

![Screenshot 2022-07-04 134428](https://user-images.githubusercontent.com/52672651/177148432-2a5981e1-802e-4b19-9219-ca76e65b1d53.png)

Chiudo la issue allora, grazie per farmi da secondo cervello!
