### ISSUE TITLE
Estrarre a.1 e a.2 nazionali per sesso e età

### ISSUE THREAD

**Issue by aborruso** [ondata/disabled-data#8]
_Originally posted by @simonabisiani in https://github.com/ondata/disabled-data/issues/5#issuecomment-1173498825_

**Comment by aborruso** [comment]
ciao @simonabisiani ho messo qui i dati nazionali, con suffisso "nazionale":
https://github.com/ondata/disabled-data/tree/main/data/disabilita-in-cifre/processing/a1-a2

Sono ok?

**Comment by simonabisiani** [comment]
Sì, vanno benissimo @aborruso!
