### ISSUE TITLE
Estrazione dati EUROSTAT, release di ottobre

### ISSUE THREAD

**Issue by simonabisiani** [ondata/disabled-data#9]
Ciao @aborruso,

Entro metà settembre, ti chiediamo di estrarci i dati dietro alle seguenti tabelle da EUROSTAT:

| TEMA                             | TABELLA                                                                 |
|----------------------------------|-------------------------------------------------------------------------|
| Access to education and training | HLTH_DE010<br>HLTH_DE020                                                |
| Access to labor market           | HLTH_DLM010<br>HLTH_DLM020<br>HLTH_DLM030<br>HLTH_DLM080<br>HLTH_DLM200 |
| Barriers to social integration   | HLTH_DSI010<br>HLTH_DSI090                                              |
| Health problems                  | HLTH_DH010<br>HLTH_DH020<br>HLTH_DH030                                  |
| Housing conditions               | HLTH_DHC010<br>HLTH_DHC020<br>HLTH_DHC030                               |
| Income distribution and poverty  | HLTH_DPE010 <br>HLTH_DPE020<br>HLTH_DPE040                              |
| Material deprivation             | HLTH_DM010 <br>HLTH_DM020<br>HLTH_DM040                                 |

Le tabelle presentano alcune variabili di interesse, ad esempio genere. Se non erro, da EUROSTAT i dati vengono scaricati nella loro intera profondità, vero? A livello geografico, siamo interessati alle figure sia per l'Italia, sia per gli altri paesi europei.

Se hai domande, dimmi pure :)

**Comment by aborruso** [comment]
Anche la @simonabisiani mi costringe a fare scraping 😀😀

Me li riappunto qui, per come sono nel bulk download:

hlth_de010
hlth_de020
hlth_dh010
hlth_dh020
hlth_dh030
hlth_dhc010
hlth_dhc020
hlth_dhc030
hlth_dlm010
hlth_dlm020
hlth_dlm030
hlth_dlm080
hlth_dlm200
hlth_dm010
hlth_dm020
hlth_dm040
hlth_dpe010
hlth_dpe020
hlth_dpe040
hlth_dsi010
hlth_dsi090

**Comment by aborruso** [comment]
Ciao @simonabisiani  ho fatto una prima estrazione che trovi descritta [qui](https://github.com/ondata/disabled-data/blob/main/data/eurostat/README.md).

Il formato _long_ mi sembra come sempre quello giusto. Le prime colonne sono dei valori di diversi dizionari (ad esempio il valore `PC`, vuol dire che i valori sono in percentuale).
Lascerei tutto per com’è, e ti metterei a disposizione dei file di risorse con il significato di ogni codice.
Che ne pensi? Se preferisci in altro modo, proponi serenamente.

**Comment by simonabisiani** [comment]
Ciao @aborruso,

ci ho finalmente dato un'occhiata - ho navigato un paio di files e mi sembra tutto a posto, completo di dettagli, e nel formato migliore possibile. 

Se riesci a fare un file di risorse con il significato dei codici usati sarebbe super, ma non c'è fretta e in emergenza me li vado a cercare io, siccome per ogni visualizzazione che creo vado comunque sempre a leggermi i metadata ecc :)

Grazie per il lavoro svolto velocemente!
Non so se vuoi chiudere la issue già adesso, ho aspettare i file di risorse; come preferisci :)
